services:
  - type: web
    repo: https://github.com/jasonpaluck/capce-xml
    plan: free
    name: capce-xml-web
    env: ruby
    region: ohio
    buildCommand: "./bin/render-build.sh"
    startCommand: bundle exec rails s
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: capce-xml-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

databases:
  - name: capce-xml-db
    plan: free
    databaseName: capce-xml-db
    user: capcexml
    region: ohio
    ipAllowList: [] # only allow internal connections